#:schema node_modules/wrangler/config-schema.json
name = "jayavira"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "d605d3486a3247669d6e0117f3eec6af" }
]

[assets]
directory = "./public"
